language: java
jdk:
  - openjdk8

script:
  - sh scripts/build.sh package

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - forbreak@163.com
    on_success: change # default: change
    on_failure: always # default: always
